### ISSUE TITLE
Main - Layout - Main Game review

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#14]
Hi Nico,

On the laravel page, I don't think this is a nice look : 

![image](https://user-images.githubusercontent.com/4339294/97210758-5576b480-17be-11eb-9e55-28926fdcd3f4.png)

Compared to the prod : 

![image](https://user-images.githubusercontent.com/4339294/97210790-60314980-17be-11eb-8e7b-ebb26efca0a3.png)

Also, I would prefer a little bit of the dark shade around the screenshots : 

![image](https://user-images.githubusercontent.com/4339294/97210833-73dcb000-17be-11eb-8616-fffc839acd51.png)

Like on prod : 

![image](https://user-images.githubusercontent.com/4339294/97210880-835bf900-17be-11eb-8a33-c3612762b544.png)

I know I'm nitpicking, but I just notice these things. Not a big deal, just my opinion.

Cheers,
Maarten

**Comment by nguillaumin** [comment]
I dislike the repeated "read more" for each review. However the striped background make sense, so I added it.
I also added padding on the dark background for screenshots.

Let me know what you think?

**Comment by stgraveyard** [comment]
Very nice. Not to be totally anal, but at the bottom : 

![image](https://user-images.githubusercontent.com/4339294/97784078-3bf9b200-1b9c-11eb-963d-b807bc2702dd.png)

That extra space could be removed. 

But very good now, thanks.

**Comment by nguillaumin** [comment]
Done.
