### ISSUE TITLE
Main - Layout - Game release detail

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#21]
Hello Nico,

Now this is an exciting part of the project! : 

![image](https://user-images.githubusercontent.com/4339294/97874410-3e354b00-1d19-11eb-9971-17f489fddb5b.png)

I love the download section, however, it doesn"t look nice on my phone. I think I solved this by removing a column or 2 in the lowest widths?  (example, remove "added" and "by" in low width). 

The first box with the text looks a bit boring. I know there is so much info, but if you look at the cpanel site, maybe we could a a box for each TAB we have? Also, we could add some search links in the text. example highlight '1988' to go to search for 1988, 'imagine' to go to search for image ... 

Also, I think the boxscans are not yet divided by release on the main site, correct? 

cheers.

**Comment by nguillaumin** [comment]
Yes I had the same thought, removing columns on smaller screen. I did just that with "Added by" and "Date", but also the SHA512 as I don't think it's useful on a phone.

For the text, I'm really keen on it. I think it's cool to have a text that looks like it's been written manually but is in fact generated from the DB. It really shines when the release has a lot of attributes (trainer, controls, protection, ...), here's a full example with a fake release:

![image](https://user-images.githubusercontent.com/762512/98023461-44a1f080-1e07-11eb-91af-6c5a4f3467cd.png)

I think tables / tab would not look that good, and are harder to read. Also having a text is better for SEO / Google than having tables

So yeah I really like the text :smile: I thought of links as well but did not do it yet as it's a bit tricky the way it's currently generated.

As for the box scans, some of them are migrated to the release, but not all. See https://prototype.atarilegend.com/games/release/1 for example.

**Comment by stgraveyard** [comment]
OK, fair enough. I do like it and you have some valid points. I do think adding some links or some trickery might spice it up a little. Download list is A OK on phone now, thanks.

**Comment by nguillaumin** [comment]
I will try to add some links, I agree it would be better.

**Comment by nguillaumin** [comment]
I added some links, please have a look!

**Comment by stgraveyard** [comment]
I love it. Maybe it can be enhanced even further in the future with more search features such as 'resolution', 'language' and so on...
