### ISSUE TITLE
Main - Layout - Main reviews

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#22]
In the main review section I think the game title is too big : 

![image](https://user-images.githubusercontent.com/4339294/97875259-696c6a00-1d1a-11eb-8460-f6c63d3da63a.png)

I also think the text display compared to the screenshot needs some work, which is aparant when we go less wide : 

![image](https://user-images.githubusercontent.com/4339294/97875350-8b65ec80-1d1a-11eb-82b4-30863c0f6ade.png)

I solved this by removing the screenshot when going small. But maybe that is just a matter of taste?

**Comment by stgraveyard** [comment]
Maybe here we can also use the wrapping of the text around the screenshot like in the news section?

**Comment by nguillaumin** [comment]
Done on the Reviews section as I said on another issue. Let me know what you think and I'll apply elsewhere if it's good.

**Comment by stgraveyard** [comment]
Hi Nico,

Yes, this is the way to go. Very nice. However, there is something off on my phone. I think it is the width of the page system. You can scroll horizontally on the phone. Because of this, when pressing a picture, you don't see the closing 'X' until you scroll to the right with your finger.

Also, I still think the font used for the game title is a bit too big, which is apparant again on the phone. 

Cheers.

**Comment by stgraveyard** [comment]
Nico, could you try this SIZE of font used in the news title on the news page, and use this size in the game reviews titles on the main review page?  I like to see the how it looks...

**Comment by nguillaumin** [comment]
I wasn't too sure what you meant with the font sizes :laughing: but I did something: Use the Audiowide font and reduce the size a bit. I did that for Articles, Reviews and Interviews, let me know what you think. I think it looks better because it's consistent with the News titles, and the Links titles as well.

For the scrolling issue, can you open a separate issue, ideally with a screenshot? I cannot reproduce it... Thanks!

**Comment by stgraveyard** [comment]
Hello Nico,

much much better. I don't know, but just for testing, maybe reduce fonts with 1 or 2 pts just to have a look? I still think it is much bigger compared to news. That being said, I don't want it to be as small as news. I like it now, I just think it could look a bit cooler when it is just a bit smaller? 

maybe I'm being stupid? 

Cheers.

**Comment by stgraveyard** [comment]
![image](https://user-images.githubusercontent.com/4339294/98462212-c81a6380-21b2-11eb-838d-0229171af1ca.png)

It does look good, but ...

**Comment by nguillaumin** [comment]
Here it is with smaller font:

![3](https://user-images.githubusercontent.com/762512/98462399-7377e800-21b4-11eb-939b-a43aac0d7b87.png)

It's the same size as News (there's no intermediate step in Bootstrap).

I don't like it personally, I think we loose the fact that it's a "heading" and it makes it harder to read by flattening the page hierarchy. I would actually do the opposite and make the News font a bit bigger to be the same size as the Reviews title:

![4](https://user-images.githubusercontent.com/762512/98462421-ab7f2b00-21b4-11eb-9038-efb12b221bf9.png)

What do you think?

**Comment by stgraveyard** [comment]
I agree with you. Please make the News font bigger and leave the other pages. I would like to test on my phone once done. Thanks.

**Comment by nguillaumin** [comment]
Done, should be live in a few minutes when the build runs.

**Comment by stgraveyard** [comment]
I love it!
