### ISSUE TITLE
Main - Layout - Games detail developer with logo

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#23]
Hi Nice,

Small weird link thingy : 

![image](https://user-images.githubusercontent.com/4339294/98304842-0b14e500-1fc1-11eb-9670-09cc7d5c14f0.png)

Again a little 'underscore' is displayed when we have a logo.

Cheers.

**Comment by nguillaumin** [comment]
Thanks, should be fixed. It's that annoying thing with HTML if you have a newline within the A tag:

```html
<a href="...">
  <i class="pen"></i><!-- HERE -->
</a>
```
