### ISSUE TITLE
Main - Layout - Interview details

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#26]
Hi Nico,

When there is no profile available, we now display an empty box : 

![image](https://user-images.githubusercontent.com/4339294/98453273-b48ddf00-2157-11eb-8982-0577fa3610e3.png)

While on the prod site it shows like this : 

![image](https://user-images.githubusercontent.com/4339294/98453281-c3749180-2157-11eb-843f-0fc5b7c40e19.png)

cheers.

**Comment by nguillaumin** [comment]
Ah yeah it's this annoying thing that in the DB sometimes there is a blank string instead of NULL, or even some spaces... I think CPANEL has a bug where it inserts blanks / spaces instead of NULL when no text is entered.

Anyway, should be fixed now.

**Comment by stgraveyard** [comment]
Thanks. Perfect.
