### ISSUE TITLE
Main - Layout - Game detail - Game info box

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#27]
Nico, 

In the game info box, it is now not possible anymore to click on the creators of the game to do a search on them, is this done on purpose? I used to love this feature : 
 
![image](https://user-images.githubusercontent.com/4339294/98453359-7c3ad080-2158-11eb-97de-f3bf75940f9b.png)

compare this to the prod site : 

![image](https://user-images.githubusercontent.com/4339294/98453365-8d83dd00-2158-11eb-8965-0aa5292e61b3.png)

The names were clickable.

Cheers.

**Comment by nguillaumin** [comment]
This was an oversight, done now.

**Comment by stgraveyard** [comment]
Very nice.

**Comment by nguillaumin** [comment]
I made it white, have a look. It breaks a bit the convention but it kind of work.

**Comment by stgraveyard** [comment]
Thanks Nico, but you know what, let's not do this. I like the look with white better, because it makes it a bit more diverse and less blue, but like you mention, let's keep it simpel. 
It is up to you, I just wanted to see it....

**Comment by nguillaumin** [comment]
Ok, I have reverted it. I agree some time that makes for a lot of underline. We can revisit the links style at some point, but we should do it globally for the whole site.
