### ISSUE TITLE
Main - Bug - Game main -Dev/Pub info box

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#29]
Hi Nico,

This is more of an old bug. For example, take Supercars 2 : 

![image](https://user-images.githubusercontent.com/4339294/98463009-96a49680-21b8-11eb-819d-4fd0fdc63ef2.png)

My idea was to be able to add bio's of people and companies, a bit like over at mobygames.com. When a company or developer has a bio, the 'i' appears. But for some reason, it happens that a company of dev has got an empty db field which than triggers the 'i'. This happens when pressing the 'i' : 

![image](https://user-images.githubusercontent.com/4339294/98463043-d1a6ca00-21b8-11eb-80c4-54a2aeec5c73.png)

Is there a way to check on the empty field or maybe a DB cleanup is needed? 

When there is text, to roll out and roll in when pressing the 'i' works beautifully <3

![image](https://user-images.githubusercontent.com/4339294/98463183-bbe5d480-21b9-11eb-83f4-48e8310f481e.png)

Cheers

**Comment by nguillaumin** [comment]
Yes this is the same issue as the Profile block on the Interviews that was empty. Some spaces in the DB. I was able to fix it, but yeah we should clean up the DB at some point. However I do think the CPANEL code is putting the blanks so we'd have to fix that first.

**Comment by stgraveyard** [comment]
Very cool this old little bug is finally gone!
