### ISSUE TITLE
Main - Layout - Game details - Develepor underscore

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#30]
Hi Nico,

Another teeny tiny bit with the developer field : 

![image](https://user-images.githubusercontent.com/4339294/98463214-f51e4480-21b9-11eb-81fc-61429dd2b6e8.png)

Thanks

**Comment by nguillaumin** [comment]
Fixed.

**Comment by stgraveyard** [comment]
Super!
