### ISSUE TITLE
Main - Layout - Game details - Screenshots do not appear on first load

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#31]
Nico,

Weird issue, but it happens frequently. I load a page and the screenshots don't appear, when I refresh, they are there, I'm using google chrome as browser : 

![image](https://user-images.githubusercontent.com/4339294/98463280-678f2480-21ba-11eb-9d64-ef6b8356b136.png)

Have you experienced this?

Maarten

**Comment by nguillaumin** [comment]
I did not see that but I use Firefox. I was able to reproduce, if you go through the search and search for Bismarck, then click on the search result, indeed the screenshots are not loading.

There's a bit of JS resizing the DIV containing the screenshots, which fails sometimes. I added a `setTimeout()` and now it seems to work...

**Comment by stgraveyard** [comment]
Seems to be working perfectly!

**Comment by stgraveyard** [comment]
Nico, 

I think I was too quick : 

![image](https://user-images.githubusercontent.com/4339294/98470393-8bb42b00-21e5-11eb-950c-10c8bd4c3767.png)

damn...

**Comment by nguillaumin** [comment]
Hm, I cannot reproduce it anymore on my side. Perhaps a cache issue, if you try to clear your cache?

Otherwise it may be a different in browser version or OS, I'm on Linux. I will try on Windows when I can.

**Comment by stgraveyard** [comment]
Did another 25 different game loads and it happened with 2 of them. Well, I will keep on trying, maybe set the timer even a bit slower?

**Comment by nguillaumin** [comment]
Good idea, I have increase it a bit.

**Comment by nguillaumin** [comment]
I tried on Windows on 2 difference PCs and could not reproduce :cry: I will close for now.

**Comment by stgraveyard** [comment]
Nico, I did not have it anymore myself since you added some more timer ;) I think this is fixed!
