### ISSUE TITLE
Main - Layout - Interview detail - Displaying the date incorrectly

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#34]
Hi Nico,

The date is not displayed correctly in the interviews. It works in the main interview section, but not at the interview itself : 

![image](https://user-images.githubusercontent.com/4339294/98469935-b94ba500-21e2-11eb-850e-55391c3b3b40.png)

Cheers.

**Comment by nguillaumin** [comment]
Thanks, fixed!
