### ISSUE TITLE
Main - Layout - Articles main missing a line space

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#35]
Hello Nico,

Just a small one ... The article section is definetely missing a 'return/line space' compared to the interviews section here : 

![image](https://user-images.githubusercontent.com/4339294/98470023-43940900-21e3-11eb-85c3-5c7fe5921a73.png)

It should 'breath' a bit more...

I also think a line could be added underneath the 'search' bottom in the review section? 

![image](https://user-images.githubusercontent.com/4339294/98470056-835af080-21e3-11eb-84e8-9c26f798e63c.png)

Cheerio.

**Comment by nguillaumin** [comment]
You're right this was inconsistent, now fixed.
