### ISSUE TITLE
Main - Layout - Review detail - Making title link to game detail

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#36]
Hi Nico,

Something I definetely used was the linking of titles. When I'm reading the review of PANG, I can not click the game name anymore like I used to do : 

![image](https://user-images.githubusercontent.com/4339294/98470302-03358a80-21e5-11eb-9ff7-a23d78aadcad.png)

I don't know if this is done on purpose, but I thought it was cool that you could go back to the main game detail page.

**Comment by nguillaumin** [comment]
Good point, this was an oversight and is now fixed. However since the link is white and underlined I'm not sure how many people will realize it's clickable... But it doesn't hurt to have it.

**Comment by stgraveyard** [comment]
I like it, but how come this link is not underlined? Shouldn't we follow the standard template?

**Comment by nguillaumin** [comment]
I guess I assume we always wanted tiles titles to look exactly the same. Here's how it would look:

![Blood_Money_review_Atari_ST_Atari_Legend](https://user-images.githubusercontent.com/762512/98470658-88ba3a00-21e7-11eb-9423-465e3113ad7c.png)

What do you think?

**Comment by stgraveyard** [comment]
Hmmm, I have nothing against it looking like this. I don't know Nico, this is a tough one. I do like your attitude of keeping links all very visible and the same, using blue and a line. But since this is a title and we want to keep titles the same ... :-D I don't know. 

Nico, could you add 1 'enter' at the last game in the Author tile? I think that would look better.

**Comment by stgraveyard** [comment]
Nico, 

I would make it 'blue' because it is a link and to stay consistent with the rest of the site.

Cheers.

**Comment by nguillaumin** [comment]
Hm I don't know I think it looks a bit weird on the home page for example:

![home](https://user-images.githubusercontent.com/762512/98470975-6de8c500-21e9-11eb-9b66-34302516dfb5.jpg)

I think I'd rather keep all tiles with a white title, even if it's a link?

**Comment by stgraveyard** [comment]
Yes, you are correct. I forgot that it is ofcourse page independant. Let's keep it white and leave it at that. Thanks.
