### ISSUE TITLE
Main - Bug - Game detail - Empty info box for authors

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#37]
Hi Nico, 

We also have this little stupid bugs for the game authors : 

![image](https://user-images.githubusercontent.com/4339294/98470786-62e16500-21e8-11eb-9415-92acb7f5dff0.png)

This is for the game Dominion.

**Comment by nguillaumin** [comment]
Ah, this is different because I also fixed it for the authors. In that specific case the profile in the DB is:

```
[url=http://shrigley.com/]
```
As it's invalid BBCode it does not show anything. Not much we can do in code, I think this has to be fixed in the DB, for example ` [url=http://shrigley.com/]Personal site[/url]`
