### ISSUE TITLE
Main - Layout - Links page (on phone)

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#39]
Hi Nico,

I think the LINKS page (even though nobody will use it) could use something extra. I have a hardtime making out which text belongs to which screenshot, especially when the screen gets smaller : 

![image](https://user-images.githubusercontent.com/4339294/98711849-d2d92200-2385-11eb-8634-6e8eb09bc766.png)

Could we do some quick tests by adding 1 or 2 'enters' below each link description and/or above each screenshot... This way adding some "breather" space...

Just an idea

**Comment by nguillaumin** [comment]
I agree, I've made some adjustments please re-check.

**Comment by stgraveyard** [comment]
Thanks Nico, but not to be pushing it, could you also try an 'enter' above the screenshot? Or if this is too much, maybe some padding at top and bottom? Is that possible in the laravell CSS? Now it looks a bit unbalanced. It is better, but maybe it can look even better ...

**Comment by nguillaumin** [comment]
No problem, happy to try things, I've done it please have a look

**Comment by stgraveyard** [comment]
I think it is perfect now in phone view, but I don't like it in wide view. Look at this : 

Wide : 

![image](https://user-images.githubusercontent.com/4339294/98988239-a3621b00-2527-11eb-9118-d2cc80e5c715.png)

phone : 

![image](https://user-images.githubusercontent.com/4339294/98988279-b4ab2780-2527-11eb-9e5f-581a9e930bac.png)

In phone it is nicely balanced, in wide not. You see?

**Comment by nguillaumin** [comment]
You're right. I didn't want the extra padding on large screens and I played a bit with it but it's unbalanced. I have made some changes, please re-check.

**Comment by stgraveyard** [comment]
OK, let me express my opinion and go hardcore. 

In phone view we are almost there, but I personally would like a tiny bit more space between the title of the site and the shot : 

![image](https://user-images.githubusercontent.com/4339294/99147918-e8e82a80-2684-11eb-94d4-a8f4887e0d1c.png)

In wide view I think we need a bit more padding : 

![image](https://user-images.githubusercontent.com/4339294/99147932-00271800-2685-11eb-9c0b-a57c645200a5.png)

I think in wide mode it is still a bit too 'pressed' and crowded ... But if you want it this way, ok for me. 

Maarten

**Comment by nguillaumin** [comment]
No problem happy to make changes, it's just that it's the kind of stuff that's hard to explain so I don't necessarily get everything you mean. I think the annotated screenshot really helped. Also maybe at some point you can try to run the prototype on your computer, adjust that stuff is really easy with Bootstrap it's just a few CSS class names to add/remove in the HTML.

Anyway, adjusted again, let me know what you think!

**Comment by stgraveyard** [comment]
Now it is perfect. And yes, I will stop being the lazy one and do some stuff myself ;-)
