### ISSUE TITLE
Main - Bug - Game release details - Issue with incompatibility list?

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#40]
Hi Nico,

Can you have a look at this. When I check the CPANEL for the game 'Birds of Prey' I find this : 

![image](https://user-images.githubusercontent.com/4339294/98712532-b8537880-2386-11eb-9cae-f276b0ae90e5.png)

But when I look in the game release details on the proto site, I see this : 

![image](https://user-images.githubusercontent.com/4339294/98712652-db7e2800-2386-11eb-93b7-fe2a0dafad3e.png)

Why are 'TT' and 'ST' displayed twice?

Cheers.

**Comment by nguillaumin** [comment]
It's a DB issue, the rows were duplicated in the DB, you could see it on the prod site as well:

![1](https://user-images.githubusercontent.com/762512/98840691-64f52f00-2447-11eb-919d-9c2901b954dd.png)

I fixed it just by re-saving the release in CPANEL. Not sure how it could happen though...
