### ISSUE TITLE
Main - Bug - Game release details - Point missing

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#41]
Nico, 

I'm browsing and reading through the site and just add what I can find. This is really minor but it seems a 'point' is missing at the end of this sentence? : 

![image](https://user-images.githubusercontent.com/4339294/98713131-8262c400-2387-11eb-9fea-46465a5c916c.png)

Am I being silly? ;-)

Cheers.

**Comment by nguillaumin** [comment]
Well spotted! Should be fixed now.
