### ISSUE TITLE
Main - Bug - Game details - Release without date not correctly displayed

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#42]
Nico,

For the  game Epic, one release does not have a release date and this is diplayed incorrectly on the game detail page : 

![image](https://user-images.githubusercontent.com/4339294/98713550-0cab2800-2388-11eb-88fa-42636fbb9f31.png)

Cheers.

**Comment by nguillaumin** [comment]
DB issue again. The date is set to '0000-00-00' instead of NULL. There were 50 rows like that affected in prod, I fixed them.

**Comment by nguillaumin** [comment]
I reimported the prod DB and it's good now, shows `[no date]`
