### ISSUE TITLE
Main - Bug - Game Detail - Game name issue

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#43]
Nico, 

Is this to be solved in the database again? 

![image](https://user-images.githubusercontent.com/4339294/98713853-70355580-2388-11eb-9739-4fba18d9f3b5.png)

The normal title is Glücksrad.

**Comment by stgraveyard** [comment]
Another one, including the names of the devs : 

![image](https://user-images.githubusercontent.com/4339294/98714029-ad99e300-2388-11eb-9451-8bed4ef302ff.png)

**Comment by nguillaumin** [comment]
Yes, same issue as the other one, should be fixed in the DB. There were only 5 games like that, so I fixed them in prod.

**Comment by nguillaumin** [comment]
I re-imported the prod DB and the game name is good now. The developers still need to be fixed in prod.

**Comment by stgraveyard** [comment]
Yes, I still need to do this. Will keep you posted. Thanks for the new update of the DB. Awesome to see all the latest interviews in the new site.
