### ISSUE TITLE
Main - Bug - Search functions not complete

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#44]
Hello Nico,

There is a little problem with the search bar on the main site, as well as in the game section. This has to do with the 'AKA' table. 

When you search 'cruise for a ...' the game title does not appear : 

![image](https://user-images.githubusercontent.com/4339294/98850123-932d3b80-2454-11eb-9cbd-69f3d1ce7274.png)

Trying this on the prod site it does work. This is because the main title is Criosiere pour un cadavre, and the AKA title is cruise for a corpse. 

This is something that we really need fixed again imo.

Cheers.

**Comment by nguillaumin** [comment]
Thanks, I completely overlooked this. Should be fixed now.
