### ISSUE TITLE
Main - Bug - Game detail - Photo and interview icon missing as well as AKA name

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#47]
Hello Nico, 

When going to the detail page of the game Vroom, the photo and interview icon, as wel as the AKA name, are missing next to Daniel Macré : 

![image](https://user-images.githubusercontent.com/4339294/99125687-e514c380-2604-11eb-940a-c26ced299bb5.png)

Compare this to the prod site :  

![image](https://user-images.githubusercontent.com/4339294/99125770-0d9cbd80-2605-11eb-828e-0fedd08a69df.png)

Now you might say, the interview is already displayed in a seperate box, but what if we have 2 people interviewed for the the same game. That is why I added this little icons. 

Please have a look and let me know what you think.

Maarten

**Comment by nguillaumin** [comment]
This was an oversight, thanks for pointing it out! Now fixed.

**Comment by stgraveyard** [comment]
Nico, the AKA name is still missing.

**Comment by nguillaumin** [comment]
Sorry, I missed that from your initial ticket! Should be fixed now.
