### ISSUE TITLE
Main - Bug - Game Detail - Edit pencil

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#49]
Nico, 

Maybe just a question. Why is there only an edit pencil next to dev en publisher en not at the people level? 

![image](https://user-images.githubusercontent.com/4339294/99147813-29937400-2684-11eb-900b-c826cdfdac35.png)

I think something could be changed here. It all depends how far we wanna go.  We could add a pencil for the game editing in total so it goes to this page (in case of the game VROOM) : http://dev.stonish.net/admin/games/games_detail.php?game_id=3132

But the individuals also have an edit page like this : 

![image](https://user-images.githubusercontent.com/4339294/99147872-8e4ece80-2684-11eb-8a9f-11cbafa544a3.png)

Also, the pencil is only visible for admins who are logged in, right? Not for all other people who are logged in? 

What do you think about this?

Maarten

**Comment by nguillaumin** [comment]
Yes, the pencil links are only available for logged-in admins. I started to put some where we have them on the old site, then I added a few more but I did not cover everything. We could definitely add more.

I added one next to the game individuals, let me know what you think and if I should put some elsewhere.

**Comment by stgraveyard** [comment]
Maybe also one next to the review and the interview?

**Comment by nguillaumin** [comment]
There are some already in the review & interview section (and articles too):

![6](https://user-images.githubusercontent.com/762512/99152509-9ae21f80-26a2-11eb-942d-cf954ca69f55.png)

![7](https://user-images.githubusercontent.com/762512/99152510-9b7ab600-26a2-11eb-9fdd-c38e53d6ab32.png)

Or did you mean somewhere else?

**Comment by stgraveyard** [comment]
maybe it is overkill, but on the vroom detail page you also have tiles to a review and an interview, I thought adding a pencil in those tiles also, but maybe too much?

**Comment by nguillaumin** [comment]
Yes I think it's too much, we should try to put them only on the "main page" of what there is to edit, rather than on every link that points to it.
