### ISSUE TITLE
Main - Layout - Interviews main - photo missing

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#50]
Nico, 

What is going on here? This person should not have a photo, yet we get this :  

![image](https://user-images.githubusercontent.com/4339294/99151358-e7296180-269a-11eb-859b-8ee455874dc8.png)

Compared to prod : 

![image](https://user-images.githubusercontent.com/4339294/99151372-fc9e8b80-269a-11eb-823d-56cb83f098ac.png)

Again proto :  

![image](https://user-images.githubusercontent.com/4339294/99151379-0aeca780-269b-11eb-887f-c685b389cdb0.png)

prod :  

![image](https://user-images.githubusercontent.com/4339294/99151416-48e9cb80-269b-11eb-9bac-641f554cc99a.png)

**Comment by nguillaumin** [comment]
Somewhat of a DB issue: the `imgext` column was set to a blank rather than NULL. But that happens sometimes so I made the code more defensive against this. Should work now.

**Comment by stgraveyard** [comment]
When I press page 4 I now get this page : 

![image](https://user-images.githubusercontent.com/4339294/99155186-f538ab80-26b5-11eb-890a-a2abca23a4b6.png)

**Comment by nguillaumin** [comment]
Fixed!
