### ISSUE TITLE
Main - Bug - Game Details - Similar game no pop up

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#51]
Hi Nico,

For the game gods, there is a similar game, but the mouse over popup with the game name does not work : 

![image](https://user-images.githubusercontent.com/4339294/99151538-46d43c80-269c-11eb-98d3-db36b862385f.png)

Please compare with prod site.

Thanks,
Maarten

**Comment by nguillaumin** [comment]
Another oversight! I did the popup well after I did the similar game tile so I forgot to apply it. Should be fixed now.
