### ISSUE TITLE
Main - Bug - Game detail - Interview tile

### ISSUE THREAD

**Issue by stgraveyard** [atari-legend/laravel-prototype#53]
Nico, 

In the game detail section, the interview tile when there is no interview photo is still displayed (this is for the game Crystals of Arborea): 

![image](https://user-images.githubusercontent.com/4339294/99155497-a3455500-26b8-11eb-8199-ee1c408f9868.png)

I would also prefer here to only display the tile if we have a picture of the person, like on the prod version.

Thanks

**Comment by nguillaumin** [comment]
Done.
